version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    # networks:
    #   - mongo-tier
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: asdf

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    # networks:
    #   - mongo-tier
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: asdf
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

  # redis1:
  #   container_name: redis1
  #   image: redis
  #   command: redis-server --requirepass asdf
  #   ports:
  #   - '6379:6379'

  app:
    image: steedude/mongo-express:latest
    command: sh -c "npm install && npm run dev"
    ports:
      - 80:8080
    working_dir: /app
    depends_on:
      - mongodb

# networks:
#   mongo-tier:
volumes:
  db-data:
