name: deploy
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SECRET }}
          script: |
            cd mongo-express/
            git pull
            docker-compose -f docker-compose-dev.yml build
            docker-compose -f docker-compose-dev.yml up -d
